### ISSUE TITLE
result.match throws error

### ISSUE THREAD

**Issue by 2426021684** [nlp-compromise/compromise#181]
`nlp_compromise.sentence("Where are you?").match("are")[0].match("are")`
`TypeError:  _match is not a function`
Version: latest from head

**Comment by spencermountain** [comment]
ha, you got me. I went to answer your question and found the same thing ;)
will fix it today. it should return another `[Result]` i believe, but will check.
i owe you a beer

**Comment by spencermountain** [comment]
so this is happening because `./match.js` requires `./result.js`, and `./result.js` requires `./match.js`.
I had no idea that javascript would let this fail silently, or just return a null.
if anyone has any good ideas.. I may just shove some code around until it works. This stuff endlessly confuses me

**Comment by 2426021684** [comment]
Recursive dependencies are not fun.

**Comment by spencermountain** [comment]
hey, got this figured out now in v7. :dancing_men:  !
https://runkit.com/583f2a3dc534df0014136221/58c82491ee89c00015029394
thanks a bunch 
cheers
