### ISSUE TITLE
Add firstnames to the lexicon

### ISSUE THREAD

**Issue by sandro-pasquali** [nlp-compromise/compromise#218]
Noticed that "Reid Hoffman" was not being picked up.

How does one go about augmenting the names db? Is that possible?

**Comment by spencermountain** [comment]
hi Sandro, that's a good question.

```javascript
lexicon = nlp.lexicon()
lexicon["reid"] = "Person" // augment it
let s = nlp.sentence('Reid Hoffman is nice', {lexicon:lexicon}); // use the new lexicon for tagging
console.log(s.tags());   //now a person => ['Person', 'Copula', 'Adjective']
```
ideally you'd be able to specify if Reid is a Male or Female name too. Will leave this open for that feature.
cheers,

**Comment by sandro-pasquali** [comment]
Thanks!

**Comment by ilyankou** [comment]
This is a little tricky, since `lexicon` consists key-value pairs and you cannot assign two values to the same key. Gender check happens from a different array, `firstnames[NAME] = 'm(f,a)'`. These happen independently and gender.js has no access to `lexicon` (only the default lexicon), so it can't pull gender even if our customized lexicon has an entry like `ilya : ['Person', 'm']`

**Comment by spencermountain** [comment]
yeah, right. I was thinking of `MalePerson` ;)
ideally firstnames.js should land in lexicon, though I haven't really thought it through

**Comment by spencermountain** [comment]
hey, gender is now passing-through as of `v6.4.5`:
```javascript
nlp.lexicon({
   reid: 'FemalePerson'
});
var t= nlp.sentence('Reid Hoffman').terms[0]
console.log(t.pos)
//{Person:true, FemalePerson:true}
console.log(t.gender())
//Female
```
unfortunately, it doesn't yet work on `nlp.Person('reid hoffman').gender()` though i suppose it should.

**Comment by spencermountain** [comment]
hey guys!
this words now!
https://runkit.com/583f2a3dc534df0014136221/58d5d0e469bd5800151ed584
weee!
