### ISSUE TITLE
v7 API feedback

### ISSUE THREAD

**Issue by spencermountain** [nlp-compromise/compromise#244]
howdy, 

[been drafting a new api](https://github.com/nlp-compromise/nlp_compromise/blob/v7/README.md)

happy for any feedback

**Comment by factormystic** [comment]
I personally don't really like the string enumerations as parameters, like `to('Question')`. This makes it a lot harder to know how to use the library because you can't just dump out object methods or use compiler tools to know if it's correct. Is this approach _really_ better than `toQuestion` or `to(Transforms.Question)`, to give to alternate implementation examples off the top of my head?

I do like the concept of limiting mutability and being able to use methods fluently. It's unclear from your proposal, for methods that return "this", if "this" is a new object with transformations applied leaving the original object unaffected (ie, an immutable approach) or if "this" is the original object, mutated.

**Comment by spencermountain** [comment]
YES 🆒 
this is exactly what i've been thinking, and I really need the help. Thanks for your help.

i agree using loose-strings like this feels not right. I stewed around about this. D3 makes a function (like `scale`) then adds methods on the prototype, so you can call `scale('param')` or `scale.fn()`, and this may be more sensible. Oof. I dunno. - 
* `nlp('').to.Question().as('whatever')`?
* `nlp('').to((t)=>t.Question()).as('whatever')`?
....😫  🌵 😫  ...

yeah, the transforms are returning a mutated `this`. It's a good question. As I see it right now, v7 will stop-short of using non-native data-structures, but happy to go this way later, if the idea lingers.

So lastly, currently our term classes have been subclassed and extend one-another - this means when a word gets tagged as a Verb, we have to re-build all the things we have already figured-out about this word from scratch - and since these objects were being passed userland data, they all had duplicate re-parsing logic - each class had basically a secondary pos-tagger.

I've been moving away from this idea this week. It's not solid yet. 
Now in v7, when you tag a word, it swaps in new transforms, get() methods, and so forth - but it stays the same term object. It's kind of a big change. Any feedback welcomed
