### ISSUE TITLE
Root form with numbers doesn't work

### ISSUE THREAD

**Issue by shaharyakir** [nlp-compromise/compromise#253]
nlp.sentence("amusing") -> "amuse" (Good)
nlp.sentence("20 amusing") -> "20 amusing" (Doesn't conjugate amusing anymore...)

**Comment by spencermountain** [comment]
hi Shahar. yeah, this is a good point.
in fact, this is one of the main reasons i've started work on a [big api change](https://github.com/nlp-compromise/nlp_compromise/blob/v7/README.md). 

so i'm a bit confused with your example. are you calling verb.conjugate()? because neither 20 or amusing (adjective) are verbs that would have that method.
anyways, this problem should be addressed in v7.
cheers

**Comment by shaharyakir** [comment]
No, I'm calling root().

i.e. - require('nlp_compromise').sentence("20 amusing").root()

Thanks for the reply - when is v7 due more or less?

**Comment by spencermountain** [comment]
sorry I didn't follow up, this works in a better way now, with `.verbs().conjugate()`
https://runkit.com/spencermountain/59a169d04038770012a4f578
cheers
