### ISSUE TITLE
fails to negate sentence

### ISSUE THREAD

**Issue by chris-hawley** [nlp-compromise/compromise#256]
sentence("apples are pears").negate() does not work. If I put the text as a statement, then the negate works.

**Comment by spencermountain** [comment]
yeah, sorry chris. this is intentional and poorly documented. The motivation was that a question cannot be negated, and a question is a sentence....
this little trickster, and others, have motivated me to start working on a [big re-write](https://github.com/nlp-compromise/nlp_compromise/blob/v7/README.md). Please let me know if you have any ideas or insight.
cheers

**Comment by chris-hawley** [comment]
I do have a really hacky solution but it will solve the problem with questions. I don’t know JS that well but here below would be the pseudo code of negate in the sentence class.
 
If (sentence is not question): run negate; return this;
Else: return this

**Comment by spencermountain** [comment]
you can also call it directly with 
```javascript
nlp.statement('apples are pears').negate()
```
cheers

**Comment by chris-hawley** [comment]
I was offering that method as a solution inside the nlp_compromise library. Below is that method inserted into the relevant code. 

below is what is present now in the sentence class
`negate() {
    return this;
  }
`

My solution: //note: the JS might not be exactly correct. also, the negate.js reference will have to be made. 

```
negate() {
    if(this.sentence_type() != 'interrogative')
       {
          oldnegate(this);
          return this;
       }
    else{
         return this;
     }
  }
```

**Comment by spencermountain** [comment]
hey chris, this is working now in v7, with a slightly different api
https://runkit.com/583f2a3dc534df0014136221/58c6d6f104249c0013ac076a
thanks!
