### ISSUE TITLE
"I am" becomes "I been"

### ISSUE THREAD

**Issue by GuyPaddock** [nlp-compromise/compromise#264]
Running the following snippet:

``` JavaScript
nlp.sentence('I am the very model of a modern major-general.').to_past().text()
```

Produces the sentence: "I been the very model of a modern major-general."

Similar results just passing "I am". I'm guessing it just doesn't have this form down.

**Comment by spencermountain** [comment]
good find!
i'm doing a [pretty-dramatic](https://github.com/nlp-compromise/nlp_compromise/tree/v7) rewrite of this logic, and it should address this in the next few weeks.
in the meantime, it looks like the culprit is [here](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/data/irregular_verbs.js#L31). sentence.to_past() should set it as the participle form, i reckon
will leave this open,
thanks!

**Comment by spencermountain** [comment]
hey Guy, just getting around to updating this. Sorry for the delay,
https://runkit.com/583f2a3dc534df0014136221/58c822e4adbd8f00147ac33c
I love that example. 
Let me know if you find anything else.
cheers!
