### ISSUE TITLE
Compress / Suffix / Prefix

### ISSUE THREAD

**Issue by jonaslund** [nlp-compromise/compromise#280]
How do you best compress, suffix and prefix list of nouns to add to the data in the build process? 

Thx

**Comment by spencermountain** [comment]
hey there,
yeah, i should document this - i just haven't done it very cleanly. What are you working on? I've been moving things around today, so heads-up.

[this is the script](https://github.com/nlp-compromise/thumb/blob/master/src/compress/compress.js) i use, which doesn't look very clean, or easy to use.

Got any other ideas for how to compress it? I came to that weird suffix object-thing because it was still readable/editable, but about 20% smaller than a straight-list.
open to anything.
