### ISSUE TITLE
Contractions not split correctly

### ISSUE THREAD

**Issue by leoseccia** [nlp-compromise/compromise#325]
Contractions are not split correctly. For example "I'm your father" produces the following: 

```
[
	[
	{
		"text": "I'm",
		"normal": "i'm",
		"tags": {
			"TitleCase": true,
			"Pronoun": true,
			"Noun": true,
			"Contraction": true,
			"Singular": true
		}
	},
	{
		"text": "",
		"normal": "",
			"tags": {
			"Contraction": true,
			"Verb": true
		}
	},
	{
		"text": "your",
		"normal": "your",
			"tags": {
			"Possessive": true,
			"Noun": true,
			"Singular": true
		}
	},
	{
		"text": "father",
		"normal": "father",
			"tags": {
			"Person": true,
			"Noun": true,
			"Singular": true
		}
	}
	]
]
```

The second term text is left empty when it probably should be "'m". Is there a reason behind this?

**Comment by spencermountain** [comment]
hey, i haven't documented this anywhere, but yeah, this is the expected behaviour. 
The reason it's important to have an 'implicit' term in there, is for the pos-tagger to know about it.
you can expand and conctract contractions [like this](https://nlp-expo.firebaseapp.com/docs#contractions)

if you really don't want them in there, you could do filter them out with `terms.filter(t=>t.text)`, but that may cause some problems when the sentence gets interpreted
cheers
