### ISSUE TITLE
Functional API

### ISSUE THREAD

**Issue by daedalus28** [nlp-compromise/compromise#407]
Great work on this! We've just started using compromise, but the API is cumbersome to use when you're doing functional programming. Libraries `lodash` have released variants (lodash/fp) which make them more friendly for functional composition, and I was hoping compromise might considering doing something similar. We closed a PR on one of our libs to use compromise instead (smartprocure/futil-js#148), but ended up writing a small layer to make the API a bit more functional:

```js
let nlp = require('compromise')
module.exports = {
  getArticle: x => nlp(x).tag('Noun').nouns().data()[0].article,
  pastTense: verb => nlp(verb).sentences(0).toPastTense().out('text')
}
```

Is there currently a better to do this sort of thing with compromise, and if not, is it something you're interested in exploring?

**Comment by spencermountain** [comment]
hey Samuel, thanks. I've been there too.  It's a good criticism.

that would be an interesting project, a `compromise/fp` with the most common features split-out as pure fns, in such a way that they can be combined and things? I'm interested to know more, and certainly not married to the current api.

fwiw, the tokenization+tagging is a lot of messy+slow stuff. This is the reason for wanting to only do it only once, so that the workflow remains `pull it apart->do stuff->put it back together`. A lot of people are parsing big texts, in cases where perf is important.

if it's helpful, in earlier versions we surfaced `nlp.people()` and `nlp.values()`... which is a little closer to a functional api i guess - but what we found is that people throw in whatever text they get, and eventually we were gonna have to parse/tag/whatever any input we receive anyway - so that's why it's one big dense function right now.

how would you imagine it?
cheers
