### ISSUE TITLE
Common but ambigious first name not returned as a person

### ISSUE THREAD

**Issue by dudleycarr** [nlp-compromise/compromise#414]
The first name "Mark" is not being returned when querying for persons. It's being identified as a noun, but not returned as person. Mark is part of the list of common first names.

For example:
```javascript
console.dir(nlp('Mark Spenser').people().out('freq'))
```

Returns:
```javascript
[ { normal: 'spenser', count: 1, percent: 100 } ]
```

**Comment by spencermountain** [comment]
hi Dudley, yikes nice find.
yeah, it looks like it's just a messy order-of-operations in the lexicon with the work mark.
you can remove it from [here](https://github.com/nlp-compromise/compromise/blob/d1c3fbe7dbfdda341c657d2f1a370561887b6902/src/lexicon/compressed/data/verbs/infinitives.js#L14) and run `npm run pack`
or otherwise, wait till v11! hopefully next week.
cheers

**Comment by spencermountain** [comment]
hey Dudley, workin' right now. sorry bout that.
https://runkit.com/spencermountain/59efd7f8adbf4a0011f7633a
thanks!

**Comment by dudleycarr** [comment]
@spencermountain thank you!
