### ISSUE TITLE
hyphenated value (ranges) do not play nice.

### ISSUE THREAD

**Issue by Announcement** [nlp-compromise/compromise#418]
given the string

> The spores are reddish-brown, roughly spherical with minute warts, measuring 7.5–11 micrometers in diameter.

executing
~~~ javascript
compromise(string).values().toNice().all().data()
~~~
gives the output

> The spores are reddish-brown, roughly spherical with minute warts, measuring 7.5–11 micrometers in diameter.

when I would expect something like

> The spores are reddish-brown, roughly spherical with minute warts, measuring seven point five to eleven micrometers in diameter.

or better yet

> The spores are reddish-brown, roughly spherical with minute warts, measuring seven and a half to eleven micrometers in diameter.

but I wouldn't exactly consider the last one "reasonable" as far as the scope of this project goes, it would be nice though. :)

**Comment by spencermountain** [comment]
hey Jacob, yeah, we can totally do that.
i'll take a look at the hyphenated numbers hopefully today. We can try to do that for the next release. This is similar to #343 

.. it's funny, i think NumberRange contractions actually do expand to "num to num". we should be able to get it working.
btw, i think you want `.toText()` instead of `.toNice()` - which is a badly named method.
https://runkit.com/spencermountain/59ef4a13daba97001200e074
cheers

**Comment by spencermountain** [comment]
hey, yeah this was caught-up on the em dash.
i think this is what you want, now in 11.2.1
```js
let str = `measuring 7.5–11 micrometers`;
let doc = nlp(str);
doc.contractions().expand();
doc.values().toText();
console.log(doc.out());
//measuring seven point five to eleven micrometers
```
